/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.student_managmentsystem;

import java.awt.CardLayout;
import java.awt.Dimension;
import java.awt.LayoutManager;

/**
 *
 * @author adambaguma
 */
public class Gui extends javax.swing.JFrame {

    /**
     * Creates new form Gui
     */
    public Gui() {
        initComponents();
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        logintoggle = new javax.swing.JToggleButton();
        loginlable = new javax.swing.JLabel();
        Parent = new javax.swing.JPanel();
        Loginscrn = new javax.swing.JPanel();
        Username = new javax.swing.JTextField();
        Password = new javax.swing.JTextField();
        loginbtn = new javax.swing.JButton();
        Newuserbtn = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        Staffcheck = new javax.swing.JCheckBox();
        Studentpage = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        Studentoutput = new javax.swing.JTextArea();
        studentdrop = new javax.swing.JComboBox<>();
        Searchtxt = new javax.swing.JTextField();
        searchbtn = new javax.swing.JButton();
        Academicspage = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTextArea2 = new javax.swing.JTextArea();
        jComboBox2 = new javax.swing.JComboBox<>();
        jTextField7 = new javax.swing.JTextField();
        jButton4 = new javax.swing.JButton();
        StudentAddForm = new javax.swing.JPanel();
        passwordtxt = new javax.swing.JPasswordField();
        firstnametxt = new javax.swing.JTextField();
        surnametxt = new javax.swing.JTextField();
        agetxt = new javax.swing.JTextField();
        Coursetxt = new javax.swing.JTextField();
        moduletxt = new javax.swing.JTextField();
        AddStudentbtn = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        passconfirmtxt = new javax.swing.JPasswordField();
        jLabel9 = new javax.swing.JLabel();
        AcademicsAddForm = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        nametxt = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        passtxt = new javax.swing.JPasswordField();
        jLabel12 = new javax.swing.JLabel();
        passtxt2 = new javax.swing.JPasswordField();
        lastnametxt = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        staffagetxt = new javax.swing.JTextField();
        crstxt = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        modulestxt = new javax.swing.JTextField();
        AddStaffbtn = new javax.swing.JButton();
        postxt = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        employmentstatus = new javax.swing.JRadioButton();
        jTextField2 = new javax.swing.JTextField();
        jLabel19 = new javax.swing.JLabel();
        loctxt = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        Addtomodulebtn = new javax.swing.JTextField();
        jLabel20 = new javax.swing.JLabel();
        modulesearchbtn = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jLabel21 = new javax.swing.JLabel();
        studenttomodule = new javax.swing.JTextField();
        jPanel3 = new javax.swing.JPanel();
        Settingbtn = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        Editbtn = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Student Management System");

        jPanel1.setBackground(new java.awt.Color(0, 204, 255));
        jPanel1.addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                jPanel1ComponentShown(evt);
            }
        });

        logintoggle.setText("Logout");
        logintoggle.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logintoggleActionPerformed(evt);
            }
        });

        loginlable.setText("Please Login");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(37, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(loginlable)
                    .addComponent(logintoggle))
                .addGap(24, 24, 24))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(101, 101, 101)
                .addComponent(loginlable)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(logintoggle)
                .addGap(27, 27, 27))
        );

        Parent.setBackground(new java.awt.Color(255, 51, 51));
        Parent.setLayout(new java.awt.CardLayout());

        Loginscrn.setMinimumSize(new java.awt.Dimension(200, 200));
        Loginscrn.setSize(new java.awt.Dimension(200, 200));

        loginbtn.setText("Login");
        loginbtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                loginbtnMouseClicked(evt);
            }
        });
        loginbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                loginbtnActionPerformed(evt);
            }
        });

        Newuserbtn.setText("Create Account");
        Newuserbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NewuserbtnActionPerformed(evt);
            }
        });

        jLabel1.setText("Enter your Name:");

        jLabel2.setText("Enter your password:");

        Staffcheck.setText("Staff");

        javax.swing.GroupLayout LoginscrnLayout = new javax.swing.GroupLayout(Loginscrn);
        Loginscrn.setLayout(LoginscrnLayout);
        LoginscrnLayout.setHorizontalGroup(
            LoginscrnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, LoginscrnLayout.createSequentialGroup()
                .addGroup(LoginscrnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(LoginscrnLayout.createSequentialGroup()
                        .addGap(34, 34, 34)
                        .addGroup(LoginscrnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel1))
                        .addGap(18, 18, 18)
                        .addGroup(LoginscrnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(LoginscrnLayout.createSequentialGroup()
                                .addComponent(Username, javax.swing.GroupLayout.PREFERRED_SIZE, 193, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 174, Short.MAX_VALUE))
                            .addGroup(LoginscrnLayout.createSequentialGroup()
                                .addComponent(Password, javax.swing.GroupLayout.PREFERRED_SIZE, 193, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(Staffcheck)
                                .addGap(0, 0, Short.MAX_VALUE))))
                    .addGroup(LoginscrnLayout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(Newuserbtn, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(47, 47, 47)
                        .addComponent(loginbtn)))
                .addGap(90, 90, 90))
        );
        LoginscrnLayout.setVerticalGroup(
            LoginscrnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(LoginscrnLayout.createSequentialGroup()
                .addGap(147, 147, 147)
                .addGroup(LoginscrnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(LoginscrnLayout.createSequentialGroup()
                        .addComponent(Username, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(40, 40, 40)
                        .addGroup(LoginscrnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Password, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Staffcheck)))
                    .addGroup(LoginscrnLayout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(47, 47, 47)
                        .addComponent(jLabel2)))
                .addGap(28, 28, 28)
                .addGroup(LoginscrnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(loginbtn)
                    .addComponent(Newuserbtn))
                .addContainerGap(119, Short.MAX_VALUE))
        );

        Parent.add(Loginscrn, "card2");

        Studentpage.setBackground(new java.awt.Color(204, 204, 204));

        Studentoutput.setColumns(20);
        Studentoutput.setRows(5);
        jScrollPane1.setViewportView(Studentoutput);

        studentdrop.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Search Students", "Search Staff", "Search Modules" }));

        searchbtn.setText("Search");
        searchbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchbtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout StudentpageLayout = new javax.swing.GroupLayout(Studentpage);
        Studentpage.setLayout(StudentpageLayout);
        StudentpageLayout.setHorizontalGroup(
            StudentpageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(StudentpageLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 355, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(42, 42, 42)
                .addGroup(StudentpageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(StudentpageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(studentdrop, 0, 178, Short.MAX_VALUE)
                        .addComponent(Searchtxt))
                    .addComponent(searchbtn))
                .addContainerGap(108, Short.MAX_VALUE))
        );
        StudentpageLayout.setVerticalGroup(
            StudentpageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(StudentpageLayout.createSequentialGroup()
                .addGroup(StudentpageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(StudentpageLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 383, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(StudentpageLayout.createSequentialGroup()
                        .addGap(138, 138, 138)
                        .addComponent(studentdrop, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(28, 28, 28)
                        .addComponent(Searchtxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(28, 28, 28)
                        .addComponent(searchbtn)))
                .addContainerGap(14, Short.MAX_VALUE))
        );

        Parent.add(Studentpage, "card3");

        jTextArea2.setColumns(20);
        jTextArea2.setRows(5);
        jScrollPane2.setViewportView(jTextArea2);

        jComboBox2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Search Students", "Search Staff", "Search Modules" }));

        jButton4.setText("Search");

        javax.swing.GroupLayout AcademicspageLayout = new javax.swing.GroupLayout(Academicspage);
        Academicspage.setLayout(AcademicspageLayout);
        AcademicspageLayout.setHorizontalGroup(
            AcademicspageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(AcademicspageLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 355, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(42, 42, 42)
                .addGroup(AcademicspageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(AcademicspageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jComboBox2, 0, 178, Short.MAX_VALUE)
                        .addComponent(jTextField7))
                    .addComponent(jButton4))
                .addContainerGap(108, Short.MAX_VALUE))
        );
        AcademicspageLayout.setVerticalGroup(
            AcademicspageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(AcademicspageLayout.createSequentialGroup()
                .addGroup(AcademicspageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(AcademicspageLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 383, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(AcademicspageLayout.createSequentialGroup()
                        .addGap(138, 138, 138)
                        .addComponent(jComboBox2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(28, 28, 28)
                        .addComponent(jTextField7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(28, 28, 28)
                        .addComponent(jButton4)))
                .addContainerGap(14, Short.MAX_VALUE))
        );

        Parent.add(Academicspage, "card4");

        StudentAddForm.setBackground(new java.awt.Color(102, 102, 102));

        passwordtxt.setText("jPasswordField1");

        AddStudentbtn.setText("Add Student");
        AddStudentbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AddStudentbtnActionPerformed(evt);
            }
        });

        jLabel3.setText("First Name");

        jLabel4.setText("Password");

        jLabel5.setText("Surname");

        jLabel6.setText("Age");

        jLabel7.setText("Course");

        jLabel8.setText("Module");

        passconfirmtxt.setText("jPasswordField1");

        jLabel9.setText("Confirm Password");

        javax.swing.GroupLayout StudentAddFormLayout = new javax.swing.GroupLayout(StudentAddForm);
        StudentAddForm.setLayout(StudentAddFormLayout);
        StudentAddFormLayout.setHorizontalGroup(
            StudentAddFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(StudentAddFormLayout.createSequentialGroup()
                .addGap(118, 118, 118)
                .addGroup(StudentAddFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(StudentAddFormLayout.createSequentialGroup()
                        .addComponent(jLabel8)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(moduletxt, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(StudentAddFormLayout.createSequentialGroup()
                        .addComponent(jLabel7)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(Coursetxt, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(StudentAddFormLayout.createSequentialGroup()
                        .addGroup(StudentAddFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5)
                            .addComponent(jLabel6)
                            .addComponent(jLabel9))
                        .addGroup(StudentAddFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(StudentAddFormLayout.createSequentialGroup()
                                .addGap(56, 56, 56)
                                .addGroup(StudentAddFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(surnametxt)
                                    .addComponent(passwordtxt)
                                    .addComponent(firstnametxt)
                                    .addComponent(passconfirmtxt, javax.swing.GroupLayout.DEFAULT_SIZE, 123, Short.MAX_VALUE)))
                            .addGroup(StudentAddFormLayout.createSequentialGroup()
                                .addGap(132, 132, 132)
                                .addComponent(agetxt, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(285, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, StudentAddFormLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(AddStudentbtn)
                .addGap(140, 140, 140))
        );
        StudentAddFormLayout.setVerticalGroup(
            StudentAddFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(StudentAddFormLayout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addGroup(StudentAddFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(StudentAddFormLayout.createSequentialGroup()
                        .addGroup(StudentAddFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(StudentAddFormLayout.createSequentialGroup()
                                .addGroup(StudentAddFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(firstnametxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel3))
                                .addGap(27, 27, 27)
                                .addGroup(StudentAddFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(passwordtxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel4))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(StudentAddFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(passconfirmtxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel9))
                                .addGap(7, 7, 7)
                                .addGroup(StudentAddFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(surnametxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel5))
                                .addGap(27, 27, 27)
                                .addComponent(agetxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLabel6))
                        .addGap(27, 27, 27)
                        .addComponent(Coursetxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel7))
                .addGap(27, 27, 27)
                .addGroup(StudentAddFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(moduletxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8))
                .addGap(18, 18, 18)
                .addComponent(AddStudentbtn)
                .addContainerGap(37, Short.MAX_VALUE))
        );

        Parent.add(StudentAddForm, "card5");

        AcademicsAddForm.setBackground(new java.awt.Color(153, 153, 153));

        jLabel10.setText("First Name");

        jLabel11.setText("Password");

        passtxt.setText("jPasswordField1");

        jLabel12.setText("Confirm Password");

        passtxt2.setText("jPasswordField1");

        jLabel13.setText("Surname");

        jLabel14.setText("Age");

        jLabel15.setText("Course");

        jLabel16.setText("Module Taught");

        AddStaffbtn.setText("Add Staff");
        AddStaffbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AddStaffbtnActionPerformed(evt);
            }
        });

        jLabel17.setText("Position");

        jLabel18.setText("Office Location");

        employmentstatus.setText("Employment Status");
        employmentstatus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                employmentstatusActionPerformed(evt);
            }
        });

        jLabel19.setText("Students Taught");

        javax.swing.GroupLayout AcademicsAddFormLayout = new javax.swing.GroupLayout(AcademicsAddForm);
        AcademicsAddForm.setLayout(AcademicsAddFormLayout);
        AcademicsAddFormLayout.setHorizontalGroup(
            AcademicsAddFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(AcademicsAddFormLayout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(AcademicsAddFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(AcademicsAddFormLayout.createSequentialGroup()
                        .addComponent(jLabel16)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(modulestxt, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(AcademicsAddFormLayout.createSequentialGroup()
                        .addComponent(jLabel15)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(crstxt, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(AcademicsAddFormLayout.createSequentialGroup()
                        .addGroup(AcademicsAddFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel10)
                            .addComponent(jLabel11)
                            .addComponent(jLabel13)
                            .addComponent(jLabel14)
                            .addComponent(jLabel12))
                        .addGroup(AcademicsAddFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(AcademicsAddFormLayout.createSequentialGroup()
                                .addGap(56, 56, 56)
                                .addGroup(AcademicsAddFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(lastnametxt)
                                    .addComponent(passtxt)
                                    .addComponent(nametxt)
                                    .addComponent(passtxt2, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(AcademicsAddFormLayout.createSequentialGroup()
                                .addGap(132, 132, 132)
                                .addComponent(staffagetxt, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 152, Short.MAX_VALUE)
                .addGroup(AcademicsAddFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, AcademicsAddFormLayout.createSequentialGroup()
                        .addGroup(AcademicsAddFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(AcademicsAddFormLayout.createSequentialGroup()
                                .addComponent(jLabel18)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(loctxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(AcademicsAddFormLayout.createSequentialGroup()
                                .addComponent(jLabel19)
                                .addGap(18, 18, 18)
                                .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(AcademicsAddFormLayout.createSequentialGroup()
                                .addComponent(jLabel17)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(postxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(49, 49, 49))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, AcademicsAddFormLayout.createSequentialGroup()
                        .addComponent(employmentstatus)
                        .addGap(75, 75, 75))
                    .addGroup(AcademicsAddFormLayout.createSequentialGroup()
                        .addGap(113, 113, 113)
                        .addComponent(AddStaffbtn)
                        .addContainerGap())))
        );
        AcademicsAddFormLayout.setVerticalGroup(
            AcademicsAddFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(AcademicsAddFormLayout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addGroup(AcademicsAddFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(AcademicsAddFormLayout.createSequentialGroup()
                        .addGroup(AcademicsAddFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(AcademicsAddFormLayout.createSequentialGroup()
                                .addGroup(AcademicsAddFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(nametxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel10)
                                    .addComponent(postxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel17))
                                .addGap(27, 27, 27)
                                .addGroup(AcademicsAddFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(passtxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel11)
                                    .addComponent(jLabel18)
                                    .addComponent(loctxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(AcademicsAddFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(AcademicsAddFormLayout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addGroup(AcademicsAddFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                            .addComponent(passtxt2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jLabel12))
                                        .addGap(7, 7, 7)
                                        .addGroup(AcademicsAddFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                            .addComponent(lastnametxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jLabel13)))
                                    .addGroup(AcademicsAddFormLayout.createSequentialGroup()
                                        .addGap(30, 30, 30)
                                        .addComponent(employmentstatus)))
                                .addGap(27, 27, 27)
                                .addGroup(AcademicsAddFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(staffagetxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel19)
                                    .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(jLabel14))
                        .addGap(27, 27, 27)
                        .addComponent(crstxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel15))
                .addGap(27, 27, 27)
                .addGroup(AcademicsAddFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(modulestxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel16))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(AddStaffbtn)
                .addContainerGap(43, Short.MAX_VALUE))
        );

        Parent.add(AcademicsAddForm, "card6");

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane3.setViewportView(jTextArea1);

        jLabel20.setText("add:");

        modulesearchbtn.setText("Add student to module");
        modulesearchbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                modulesearchbtnActionPerformed(evt);
            }
        });

        jButton3.setText("Edit Module");

        jLabel21.setText("to module:");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 299, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(32, 32, 32)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton3)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(8, 8, 8)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(studenttomodule, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel21)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(Addtomodulebtn, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(29, 29, 29)
                                .addComponent(modulesearchbtn))
                            .addComponent(jLabel20))))
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(jScrollPane3)
                .addContainerGap())
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addComponent(jLabel20)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(studenttomodule, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel21)
                .addGap(8, 8, 8)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Addtomodulebtn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(modulesearchbtn))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 226, Short.MAX_VALUE)
                .addComponent(jButton3)
                .addGap(25, 25, 25))
        );

        Parent.add(jPanel2, "card7");

        jPanel3.setBackground(new java.awt.Color(102, 204, 0));

        Settingbtn.setText("Settings");
        Settingbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SettingbtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Settingbtn)
                .addContainerGap(16, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(Settingbtn)
                .addContainerGap(181, Short.MAX_VALUE))
        );

        jPanel4.setBackground(new java.awt.Color(204, 204, 0));

        Editbtn.setText("Edit Details");
        Editbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EditbtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(Editbtn)
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Editbtn)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jButton1.setText("Back");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton1)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(Parent, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(Parent, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton1)
                .addContainerGap(14, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void AddStudentbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AddStudentbtnActionPerformed
        application.Add("sFile.csv", firstnametxt.getText(), surnametxt.getText(), Integer.parseInt(agetxt.getText()), Coursetxt.getText(), moduletxt.getText(), String.valueOf(passwordtxt.getPassword()));  
        CardLayout cl = (CardLayout)Parent.getLayout();
            cl.show(Parent, "card2");// TODO add your handling code here:
    }//GEN-LAST:event_AddStudentbtnActionPerformed

    private void AddStaffbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AddStaffbtnActionPerformed
                // TODO add your handling code here:
    }//GEN-LAST:event_AddStaffbtnActionPerformed

    private void employmentstatusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_employmentstatusActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_employmentstatusActionPerformed

    private void SettingbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SettingbtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_SettingbtnActionPerformed

    private void loginbtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_loginbtnMouseClicked
    if (1==1){ //Search if user isin the database
        //if student = true
        

        }        // TODO add your handling code here:
    }//GEN-LAST:event_loginbtnMouseClicked

    private void searchbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchbtnActionPerformed
        // TODO add your handling code here:
        Editbtn.setVisible(true);
                Settingbtn.setVisible(true);
        if(studentdrop.getSelectedItem().toString() == "Search Students"){
            Studentoutput.setText(application.Search("sFile.csv",Searchtxt.getText()));
        }else if (studentdrop.getSelectedItem().toString() == "Search Staff"){
            Studentoutput.setText(application.Search("aFile.csv",Searchtxt.getText()));
        }else if (studentdrop.getSelectedItem().toString() == "Search Modules"){
           Studentoutput.setText( application.moduleDetails(Searchtxt.getText()));
        }else{
            Studentoutput.setText("oopppss something went wrong");
        }
        
    }//GEN-LAST:event_searchbtnActionPerformed

    private void loginbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loginbtnActionPerformed
       
        if (Staffcheck.isSelected()==true){
            application.Search("aFile.csv",Username.getText());
//            if (application.login("aFile.csv",Password.getText()) == false){
//                  loginlable.setText("wrong password");
//             }else{
//                loginlable.setText(application.Search("aFile.csv",Username.getText()));
                 CardLayout cl = (CardLayout)Parent.getLayout();
            cl.show(Parent, "card4");
//            
//             
//             }
             
            
           
            
            
        }else if (Staffcheck.isSelected()==false){
            application.Search("sFile.csv",Username.getText());
//             if (application.login("sFile.csv",Password.getText()) == false){
//                  loginlable.setText("wrong password");
//             }else{
//                 
                 CardLayout cl = (CardLayout)Parent.getLayout();
            cl.show(Parent, "card3");
            // loginlable.setText(application.Search("sFile.csv",Username.getText()));
//             }
            
        }else{
            loginlable.setText( "an error occured");
        }
        
        
    }//GEN-LAST:event_loginbtnActionPerformed

    private void NewuserbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NewuserbtnActionPerformed
        if(Staffcheck.isSelected()==true){
            CardLayout cl = (CardLayout)Parent.getLayout();
        cl.show(Parent,"card6");  
        }else{
        CardLayout cl = (CardLayout)Parent.getLayout();
        cl.show(Parent,"card5");  
        }// TODO add your handling code here:
    }//GEN-LAST:event_NewuserbtnActionPerformed

    private void logintoggleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logintoggleActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_logintoggleActionPerformed

    private void EditbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EditbtnActionPerformed
    CardLayout cl = (CardLayout)Parent.getLayout();       // TODO add your handling code here:
    cl.show(Parent,"card5"); //replace with edit user panel!! probably card6
    }//GEN-LAST:event_EditbtnActionPerformed

    private void jPanel1ComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_jPanel1ComponentShown
    Editbtn.setVisible(false);
                Settingbtn.setVisible(false);        // TODO add your handling code here:
    }//GEN-LAST:event_jPanel1ComponentShown

    private void modulesearchbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_modulesearchbtnActionPerformed
    application.ModuleAdd(Addtomodulebtn.getText(),studenttomodule.getText()); 
    CardLayout cl = (CardLayout)Parent.getLayout();       // TODO add your handling code here:
    cl.show(Parent,"card4");// TODO add your handling code here:
    }//GEN-LAST:event_modulesearchbtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Gui.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Gui.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Gui.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Gui.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Gui().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel AcademicsAddForm;
    private javax.swing.JPanel Academicspage;
    private javax.swing.JButton AddStaffbtn;
    private javax.swing.JButton AddStudentbtn;
    private javax.swing.JTextField Addtomodulebtn;
    private javax.swing.JTextField Coursetxt;
    private javax.swing.JButton Editbtn;
    private javax.swing.JPanel Loginscrn;
    private javax.swing.JButton Newuserbtn;
    private javax.swing.JPanel Parent;
    private javax.swing.JTextField Password;
    private javax.swing.JTextField Searchtxt;
    private javax.swing.JButton Settingbtn;
    private javax.swing.JCheckBox Staffcheck;
    private javax.swing.JPanel StudentAddForm;
    private javax.swing.JTextArea Studentoutput;
    private javax.swing.JPanel Studentpage;
    private javax.swing.JTextField Username;
    private javax.swing.JTextField agetxt;
    private javax.swing.JTextField crstxt;
    private javax.swing.JRadioButton employmentstatus;
    private javax.swing.JTextField firstnametxt;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JComboBox<String> jComboBox2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTextArea jTextArea2;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField7;
    private javax.swing.JTextField lastnametxt;
    private javax.swing.JTextField loctxt;
    private javax.swing.JButton loginbtn;
    private javax.swing.JLabel loginlable;
    private javax.swing.JToggleButton logintoggle;
    private javax.swing.JButton modulesearchbtn;
    private javax.swing.JTextField modulestxt;
    private javax.swing.JTextField moduletxt;
    private javax.swing.JTextField nametxt;
    private javax.swing.JPasswordField passconfirmtxt;
    private javax.swing.JPasswordField passtxt;
    private javax.swing.JPasswordField passtxt2;
    private javax.swing.JPasswordField passwordtxt;
    private javax.swing.JTextField postxt;
    private javax.swing.JButton searchbtn;
    private javax.swing.JTextField staffagetxt;
    private javax.swing.JComboBox<String> studentdrop;
    private javax.swing.JTextField studenttomodule;
    private javax.swing.JTextField surnametxt;
    // End of variables declaration//GEN-END:variables
}
